name: lasenet
channels:
  - defaults
  - conda-forge
dependencies:
  # - openblas
  - python
  - pandas
  - numpy
  - scipy
  - tensorflow
  - scikit-learn
  - matplotlib
  # - plotnine
  - tqdm=4.59.0
  # - docopt=0.6.2
  - jupyterlab
  - seaborn
  - pytables
  
  # - python-kaleido
  - pip:
      - mat73
      - keras-hypetune
      - evidential-deep-learning
      # - sentencepiece
      # - torchvision      
      - jupyter_contrib_nbextensions
      # - sacrebleu
      # - nltk
      - timeout_decorator